accent = "#74b2e2"
cursor = "#eff4f2"
foreground = "#eff4f2"
background = "#363334"
selection_foreground = "#eff4f2"
selection_background = "#74b2e2"

color0 = "#363334"
color1 = "#d05e58"
color2 = "#6ab8cd"
color3 = "#f9a54d"
color4 = "#74b2e2"
color5 = "#c0a5b4"
color6 = "#8cd3e8"
color7 = "#b7d0ca"
color8 = "#5d353c"
color9 = "#e7a09d"
color10 = "#acdae7"
color11 = "#ffd2a2"
color12 = "#beddf4"
color13 = "#e6dbe2"
color14 = "#d8f1f8"
color15 = "#eff4f2"
